In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
import contextily as cx
import imageio
import os

In [3]:
data_df = pd.read_csv("gdf_clustered.csv")
gdf = gpd.GeoDataFrame(
    data_df, geometry=gpd.points_from_xy(data_df["x"], data_df["y"]), crs="EPSG:4326"
)
clusters = pd.Categorical(gdf["cluster_kmeans"], categories=set(gdf["cluster_kmeans"]), ordered=False)
gdf["cluster_kmeans"] = clusters
gdf.head()

,Unnamed: 0,I_CUADRO,OBJECTID,Join_Count,TARGET_FID,ID_HILLO,ID_SON,ANYO,FOLIO,SEXO,...,Unnamed: 69,day,week,month,year,dayofyear,FD,FHD,geometry,cluster_kmeans
0,22,2010-08-30,20,1,236,250,6904,0,929,mujer,...,NaN,30,35,8,2010,242,0,1,POINT (-111.0155 29.13418),0
1,23,2010-09-01,25,1,241,255,6927,0,976,hombre,...,NaN,1,35,9,2010,244,0,1,POINT (-110.96435 29.13623),0
2,24,2010-09-02,26,1,242,256,6928,0,977,mujer,...,NaN,2,35,9,2010,245,1,0,POINT (-110.96647 29.1374),1
3,25,2010-09-02,27,1,243,257,6929,0,978,hombre,...,NaN,2,35,9,2010,245,1,0,POINT (-110.96414 29.13722),0
4,26,2010-09-02,33,1,249,262,6944,0,997,hombre,...,NaN,2,35,9,2010,245,1,0,POINT (-110.9677 29.12675),0

In [18]:
weeks = gdf["week"].unique()
weeks = np.arange(weeks.min(), weeks.max()+1)
weeks

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52])

In [42]:
folder = "./mapa_clusters_semanal"
weekly_clustered_map_images = []

In [ ]:
for i, week_num in enumerate(weeks):
    if i == 0:
        week_gdf = gdf[gdf["week"] == weeks[0]]
    else:
        week_gdf = gpd.GeoDataFrame( pd.concat( [week_gdf, gdf[gdf["week"] == weeks[i]]], ignore_index=True) )

    fig, ax = plt.subplots(figsize=(10, 10))
    week_gdf.plot(ax=ax, figsize=(8, 8), alpha=0.5, column="cluster_kmeans", legend=True, cmap='tab10', markersize=8)
    ax.set_title(f"Casos por Cluster - Semana {week_num}")
    ax.set_xlim(-111.1, -110.85)
    ax.set_ylim(28.97, 29.25)

    cx.add_basemap(ax=ax, crs="EPSG:4326", source=cx.providers.CartoDB.Voyager)

    filename = f'mapa_clusters_semanal_{week_num}.png'
    plt.savefig(os.path.join(folder,filename))
    weekly_clustered_map_images.append(imageio.imread(os.path.join(folder,filename)))

imageio.mimsave(os.path.join(folder,'mapa_clusters_semanal.gif'), weekly_clustered_map_images, fps=3)

## Animation for Cluster 0

In [44]:
gdf_cluster_0 = gdf[gdf["cluster_kmeans"] == 0]
gdf_cluster_0.head()

,Unnamed: 0,I_CUADRO,OBJECTID,Join_Count,TARGET_FID,ID_HILLO,ID_SON,ANYO,FOLIO,SEXO,...,Unnamed: 69,day,week,month,year,dayofyear,FD,FHD,geometry,cluster_kmeans
0,22,2010-08-30,20,1,236,250,6904,0,929,mujer,...,NaN,30,35,8,2010,242,0,1,POINT (-111.0155 29.13418),0
1,23,2010-09-01,25,1,241,255,6927,0,976,hombre,...,NaN,1,35,9,2010,244,0,1,POINT (-110.96435 29.13623),0
3,25,2010-09-02,27,1,243,257,6929,0,978,hombre,...,NaN,2,35,9,2010,245,1,0,POINT (-110.96414 29.13722),0
4,26,2010-09-02,33,1,249,262,6944,0,997,hombre,...,NaN,2,35,9,2010,245,1,0,POINT (-110.9677 29.12675),0
5,27,2010-09-03,28,1,244,258,6930,0,979,mujer,...,NaN,3,35,9,2010,246,1,0,POINT (-110.97021 29.13076),0

In [45]:
weeks = gdf_cluster_0["week"].unique()
weeks = np.arange(weeks.min(), weeks.max()+1)
weeks

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52])

In [46]:
folder_0 = "./mapa_cluster_0_semanal"
weekly_cluster_0_map_images = []

In [ ]:
for i, week_num in enumerate(weeks):
    if i == 0:
        week_gdf = gdf_cluster_0[gdf_cluster_0["week"] == weeks[0]]
    else:
        week_gdf = gpd.GeoDataFrame( pd.concat( [week_gdf, gdf_cluster_0[gdf_cluster_0["week"] == weeks[i]]], ignore_index=True) )

    fig, ax = plt.subplots(figsize=(10, 10))
    week_gdf.plot(ax=ax, figsize=(8, 8), alpha=0.5, column="cluster_kmeans", legend=True, cmap='tab10', markersize=8)
    ax.set_title(f"Casos de Cluster 0 - Semana {week_num}")
    ax.set_xlim(-111.1, -110.85)
    ax.set_ylim(28.97, 29.25)

    cx.add_basemap(ax=ax, crs="EPSG:4326", source=cx.providers.CartoDB.Voyager)

    filename = f'mapa_cluste_0_semanal_{week_num}.png'
    plt.savefig(os.path.join(folder_0,filename))
    weekly_cluster_0_map_images.append(imageio.imread(os.path.join(folder_0,filename)))

imageio.mimsave(os.path.join(folder_0,'mapa_cluster_0_semanal.gif'), weekly_cluster_0_map_images, fps=3)

## Animation for Cluster 1

In [48]:
gdf_cluster_1 = gdf[gdf["cluster_kmeans"] == 1]
gdf_cluster_1.head()

,Unnamed: 0,I_CUADRO,OBJECTID,Join_Count,TARGET_FID,ID_HILLO,ID_SON,ANYO,FOLIO,SEXO,...,Unnamed: 69,day,week,month,year,dayofyear,FD,FHD,geometry,cluster_kmeans
2,24,2010-09-02,26,1,242,256,6928,0,977,mujer,...,NaN,2,35,9,2010,245,1,0,POINT (-110.96647 29.1374),1
9,31,2010-09-04,34,1,250,264,6946,0,999,mujer,...,NaN,4,35,9,2010,247,1,0,POINT (-110.9632 29.13637),1
11,33,2010-09-04,48,1,264,278,7005,0,1063,mujer,...,NaN,4,35,9,2010,247,1,0,POINT (-110.96246 29.13126),1
22,44,2010-09-07,49,1,265,279,7006,0,1064,mujer,...,NaN,7,36,9,2010,250,1,0,POINT (-110.96351 29.13063),1
25,47,2010-09-08,38,1,254,268,6972,0,1028,hombre,...,NaN,8,36,9,2010,251,1,0,POINT (-110.96647 29.1374),1

In [49]:
weeks = gdf_cluster_1["week"].unique()
weeks = np.arange(weeks.min(), weeks.max()+1)
weeks

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52])

In [50]:
folder_1 = "./mapa_cluster_1_semanal"
weekly_cluster_1_map_images = []

In [ ]:
for i, week_num in enumerate(weeks):
    if i == 0:
        week_gdf = gdf_cluster_1[gdf_cluster_1["week"] == weeks[0]]
    else:
        week_gdf = gpd.GeoDataFrame( pd.concat( [week_gdf, gdf_cluster_1[gdf_cluster_1["week"] == weeks[i]]], ignore_index=True) )

    fig, ax = plt.subplots(figsize=(10, 10))
    week_gdf.plot(ax=ax, figsize=(8, 8), alpha=0.5, column="cluster_kmeans", legend=True, cmap='tab10', markersize=8)
    ax.set_title(f"Casos de Cluster 1 - Semana {week_num}")
    ax.set_xlim(-111.1, -110.85)
    ax.set_ylim(28.97, 29.25)

    cx.add_basemap(ax=ax, crs="EPSG:4326", source=cx.providers.CartoDB.Voyager)

    filename = f'mapa_cluste_1_semanal_{week_num}.png'
    plt.savefig(os.path.join(folder_1,filename))
    weekly_cluster_1_map_images.append(imageio.imread(os.path.join(folder_1,filename)))

imageio.mimsave(os.path.join(folder_1,'mapa_cluster_1_semanal.gif'), weekly_cluster_1_map_images, fps=3)

## Animation for Cluster 2

In [52]:
gdf_cluster_2 = gdf[gdf["cluster_kmeans"] == 2]
gdf_cluster_2.head()

,Unnamed: 0,I_CUADRO,OBJECTID,Join_Count,TARGET_FID,ID_HILLO,ID_SON,ANYO,FOLIO,SEXO,...,Unnamed: 69,day,week,month,year,dayofyear,FD,FHD,geometry,cluster_kmeans
21,43,2010-09-07,40,1,256,270,6990,0,1046,hombre,...,NaN,7,36,9,2010,250,1,0,POINT (-110.93703 29.0493),2
39,61,2010-09-11,2356,1,2582,282,7028,0,1089,hombre,...,NaN,11,36,9,2010,254,1,0,POINT (-110.97181 29.06674),2
97,119,2010-09-20,174,1,390,409,7227,0,1309,mujer,...,NaN,20,38,9,2010,263,1,0,POINT (-110.96615 29.10357),2
109,131,2010-09-21,136,2,352,371,7168,0,1243,hombre,...,NaN,21,38,9,2010,264,0,1,POINT (-110.97394 29.09543),2
126,148,2010-09-22,182,1,398,417,7236,0,1318,hombre,...,NaN,22,38,9,2010,265,1,0,POINT (-110.94555 29.04321),2

In [53]:
weeks = gdf_cluster_2["week"].unique()
weeks = np.arange(weeks.min(), weeks.max()+1)
weeks

array([36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52])

In [54]:
folder_2 = "./mapa_cluster_2_semanal"
weekly_cluster_2_map_images = []

In [ ]:
for i, week_num in enumerate(weeks):
    if i == 0:
        week_gdf = gdf_cluster_2[gdf_cluster_2["week"] == weeks[0]]
    else:
        week_gdf = gpd.GeoDataFrame( pd.concat( [week_gdf, gdf_cluster_2[gdf_cluster_2["week"] == weeks[i]]], ignore_index=True) )

    fig, ax = plt.subplots(figsize=(10, 10))
    week_gdf.plot(ax=ax, figsize=(8, 8), alpha=0.5, column="cluster_kmeans", legend=True, cmap='tab10', markersize=8)
    ax.set_title(f"Casos de Cluster 2 - Semana {week_num}")
    ax.set_xlim(-111.1, -110.85)
    ax.set_ylim(28.97, 29.25)

    cx.add_basemap(ax=ax, crs="EPSG:4326", source=cx.providers.CartoDB.Voyager)

    filename = f'mapa_cluste_2_semanal_{week_num}.png'
    plt.savefig(os.path.join(folder_2,filename))
    weekly_cluster_2_map_images.append(imageio.imread(os.path.join(folder_2,filename)))

imageio.mimsave(os.path.join(folder_2,'mapa_cluster_2_semanal.gif'), weekly_cluster_2_map_images, fps=3)

## Animation for Count

In [4]:
gdf.head()

,Unnamed: 0,I_CUADRO,OBJECTID,Join_Count,TARGET_FID,ID_HILLO,ID_SON,ANYO,FOLIO,SEXO,...,Unnamed: 69,day,week,month,year,dayofyear,FD,FHD,geometry,cluster_kmeans
0,22,2010-08-30,20,1,236,250,6904,0,929,mujer,...,NaN,30,35,8,2010,242,0,1,POINT (-111.0155 29.13418),0
1,23,2010-09-01,25,1,241,255,6927,0,976,hombre,...,NaN,1,35,9,2010,244,0,1,POINT (-110.96435 29.13623),0
2,24,2010-09-02,26,1,242,256,6928,0,977,mujer,...,NaN,2,35,9,2010,245,1,0,POINT (-110.96647 29.1374),1
3,25,2010-09-02,27,1,243,257,6929,0,978,hombre,...,NaN,2,35,9,2010,245,1,0,POINT (-110.96414 29.13722),0
4,26,2010-09-02,33,1,249,262,6944,0,997,hombre,...,NaN,2,35,9,2010,245,1,0,POINT (-110.9677 29.12675),0

In [10]:
cluster_dummies = pd.get_dummies(gdf["cluster_kmeans"], prefix="cluster", dtype="int")
gdf["cluster_0"] = cluster_dummies["cluster_0"]
gdf["cluster_1"] = cluster_dummies["cluster_1"]
gdf["cluster_2"] = cluster_dummies["cluster_2"]

In [11]:
# Spike count by day

# Actual counts:
gdf_counts = pd.DataFrame(gdf.groupby("dayofyear")["FD_FHD"].count())
gdf_counts["week"] = gdf.groupby("dayofyear")["week"].mean().astype("int")
gdf_counts["cluster_0"] = gdf.groupby("dayofyear")["cluster_0"].sum()
gdf_counts["cluster_1"] = gdf.groupby("dayofyear")["cluster_1"].sum()
gdf_counts["cluster_2"] = gdf.groupby("dayofyear")["cluster_2"].sum()

# Cumulative total:
gdf_counts["cluster_0_cumsum"] = gdf_counts["cluster_0"].cumsum()
gdf_counts["cluster_1_cumsum"] = gdf_counts["cluster_1"].cumsum()
gdf_counts["cluster_2_cumsum"] = gdf_counts["cluster_2"].cumsum()
# Rolling mean:
gdf_counts["cluster_0_mean"] = gdf_counts["cluster_0"].rolling(7).mean()
gdf_counts["cluster_1_mean"] = gdf_counts["cluster_1"].rolling(7).mean()
gdf_counts["cluster_2_mean"] = gdf_counts["cluster_2"].rolling(7).mean()

gdf_counts.tail()

,FD_FHD,week,cluster_0,cluster_1,cluster_2,cluster_0_cumsum,cluster_1_cumsum,cluster_2_cumsum,cluster_0_mean,cluster_1_mean,cluster_2_mean
dayofyear,,,,,,,,,,,
354,1,51,1,0,0,1329,721,649,1.285714,0.285714,0.857143
358,1,51,0,0,1,1329,721,650,1.285714,0.142857,1.000000
361,1,52,0,0,1,1329,721,651,1.000000,0.142857,1.142857
362,2,52,0,1,1,1329,722,652,0.714286,0.285714,1.285714
365,3,52,1,1,1,1330,723,653,0.571429,0.428571,1.428571